auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('watchlist', views.watchlist, name="watchlist"),
    path('watchlist/<int:listing_id>', views.add_to_watchlist, name="add_to_watchlist"),
    path('create_listing', views.listing_view, name="listing"),
    path('comment', views.comment, name="comment"),
    path('bid',views.bid, name="bid"),
    path('categories', views.categories, name="categories"),
    path('categories/<str:category>', views.category, name="category"),
    path('close_auction/<int:listing_id>', views.close_auction, name="close_auction"),
    path('<str:name>', views.current_listing, name="current_listing")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),




    path("__reload__/", include("django_browser_reload.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
# Bismillahirahmanirahim
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    #It already makes fields for name, email and password
    #If we want we can make more fields here. But I am leaving with as it is.
    pass


class Listing(models.Model):
    CATEGORY_CHOICES = [
        ('Electronics','Electronics'),
        ('Toys','Toys'),
        ('Home','Home'),
        ('Fashion','Fashion'),
        ('Magical','Magical')
    ]
    title = models.CharField(max_length= 50)
    description = models.TextField(max_length=1000)
    starting = models.DecimalField(max_digits=10, decimal_places= 2)
    image_url = models.URLField(blank=True, max_length= 1000)
    category = models.CharField(max_length=50,choices=CATEGORY_CHOICES, blank=True)
    listed_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name= 'listings')
    time_created = models.DateTimeField(auto_now_add=True) #Records the time when an entry is created.
    # It wont change when it is updated.

    # Records whether the listing is Active or not.
    Active = models.BooleanField(default=True)
    def __str__(self):
        return f'{self.title} starting from {self.starting} by {self.listed_by}'
    

class bids(models.Model):
    listing = models.ForeignKey(Listing, on_delete= models.CASCADE, related_name= 'bids')
    bidder = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'biddings', null = True)
    bid = models.DecimalField(max_digits=10, decimal_places= 2, null = True)

    class Meta:
        verbose_name = 'bid'

    def __str__(self):
        return f'{self.bidder} bidded {self.bid} on {self.listing}'



class comments(models.Model):
    listing = models.ForeignKey(Listing,on_delete=models.CASCADE, related_name='comments_on_listing',null = True)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users_comments', null = True)
    comment = models.TextField(max_length=1000, null=True)
    posted = models.DateField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'comment'

    def __str__(self):
        return f'{self.id}: {self.commenter} commented on {self.listing}'

class Watchlist(models.Model):
    watch_lister = models.OneToOneField(User, on_delete= models.CASCADE)
    watch_list_items = models.ManyToManyField(Listing, related_name='watchlist')

    def __str__(self):
        return f"{self.watch_lister}'s watchlist"

auctions/forms.py
# Bismillahirahmanirahim
from django import forms
from .models import Listing, bids, comments
from django.core.exceptions import ValidationError
from django.db import models


#Making a Form for listing.
class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title','description','starting','image_url','category']
    # Adding Tailwind
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'placeholder': 'Enter listing title',
            }),
            'description': forms.Textarea(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'rows': 4,
                'placeholder': 'Enter description',
            }),
            'starting': forms.NumberInput(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'placeholder': 'Starting price',
            }),
            'image_url': forms.TextInput(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'placeholder': 'Enter image URL',
            }),
            'category': forms.Select(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
            }),
        }
    

class BiddingForm(forms.ModelForm):
    # A form receives the listing_id but I will inshallah not submit it to the user.
    listing_id = forms.IntegerField(widget = forms.HiddenInput()) #Listing id is an integer so use an integer field.
    def clean(self):
        # Calls the parents class clean method to get the cleaned data.
        cleaned_data =  super().clean()
        # This ensures that all standard validation for fields like listing and bid is completed first.
        # In other words it is validated according to the default clean.

        ### After that below we write our custom validations.

        # Extract data for listing and biding
        listing_id = cleaned_data.get('listing_id')
        listing = Listing.objects.get(id=listing_id)
        bid = cleaned_data.get('bid')

        # Get the highest bid for the listing until now
        highest_bid = listing.bids.aggregate(max_bid = models.Max('bid'))['max_bid']
        # Check if the bid is atleast the starting price
        if highest_bid is None and bid < listing.starting:
            raise ValidationError(f'The bid must be atleast {listing.starting}')
        

        # Check if the bid is greater than the highest bid
        if highest_bid is not None and bid <= highest_bid:
            raise ValidationError(f'The Bid must be greater than {highest_bid}')

        # Return the cleaned data if everything is valid.

        # After we have performed custom validation we return the cleaned data so that django can use it
        # for further processing
        return cleaned_data


    class Meta:
        model = bids
        fields = ['bid']
        widgets = {
            'bid': forms.NumberInput(attrs={
                'class': 'rounded-md my-2 w-full border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
                'placeholder': 'Bid',
            })}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bid'].label = ''  # Remove the label
    

class CommentForm(forms.ModelForm):

    # A form receives the listing_id but I will inshallah not submit it to the user.
    listing_id = forms.IntegerField(widget = forms.HiddenInput()) #Listing id is an integer so use an integer field.

    class Meta:
        model = comments
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'w-full p-3 border rounded-lg shadow-sm focus:outline-none focus:ring focus:ring-blue-300',
                'rows':7,
                'placeholder': 'Write your comment here...'
            })
        }

auctions/views.py
# Bismillahirahmanirahim
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError, models
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required


from .models import User, Listing, Watchlist
from .forms import ListingForm, BiddingForm, CommentForm

def index(request):
    listings = Listing.objects.annotate(highest_bid=models.Max('bids__bid')).filter(Active=True)
    return render(request, "auctions/index.html",{
        'listings':listings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


# For Creating Listing
@login_required
def listing_view(request):
    # If the user submits a form
    if request.method == 'POST':
        # Make a form and bound the data submitted with it in order to validate and save it.
        # As if data wont be bounded their wont be data in form to validate.
        form = ListingForm(request.POST)
        if form.is_valid():
            listiing = form.save(commit=False)
            #This saves the form but doesn't commit it to the database yet. 
            # This allows you to manually assign the listed_by field. 
            listiing.listed_by = request.user
            form.save()
            return HttpResponseRedirect(reverse("index"))
    return render(request, "auctions/listing.html",{'form': ListingForm()})


def current_listing(request, name):
    try:
        current = Listing.objects.get(title = name)
        #Makes bidding form and gives a default value for listing_id
        bidding_form = BiddingForm(initial = {'listing_id': current.id})
        
        # Get the highest bid if placed any
        highest_bid = current.bids.aggregate(max_bid = models.Max('bid'))['max_bid']
        biddings = current.bids.count() # Total number of bidings on the listing
        if highest_bid is not None:
            highest_bidder = current.bids.get(bid = highest_bid).bidder # The highest bidder
        else:
            highest_bidder = None
        comments = current.comments_on_listing.all() # All the comments on the listing
        comment_form = CommentForm(initial= {'listing_id': current.id})

        return render(request, "auctions/current_listing.html",{
            'title': name,
            'listing': current,
            'bidding_form': bidding_form,
            'highest_bid': highest_bid,
            'biddings': biddings,
            'highest_bidder': highest_bidder,
            'comments': comments,
            'comment_form': comment_form
        })
    except:
        return HttpResponse(f'Sorry no listing with the title {name}')

@login_required
def bid(request):
    """A func for handling the bidding"""
    if request.method == 'POST':
        #Makes a form and bound the data with it. Without it you wont be able to validate it.
        form = BiddingForm(request.POST)

        if form.is_valid():
            #The next step save the form but does not upload it to the database.
            bid = form.save(commit=False)
            bid.bidder = request.user
            bid.listing = get_object_or_404(Listing, id= form.cleaned_data['listing_id'])
            bid.save()
            return HttpResponseRedirect(reverse('current_listing',args=[bid.listing.title]))
        else:
            listing_id = form.cleaned_data.get('listing_id')  # Get listing_id from the form
            listing = get_object_or_404(Listing, id=listing_id)
            highest_bid = listing.bids.aggregate(max_bid = models.Max('bid'))['max_bid']
            try:
                highest_bidder = listing.bids.get(bid = highest_bid).bidder
            except:
                highest_bidder = None
            return render(request, "auctions/current_listing.html", {
                'title':listing.title,
                'listing': listing,
                'bidding_form': form,
                'highest_bid': highest_bid,
                'biddings': listing.bids.count(),
                'highest_bidder': highest_bidder,
                'comments': listing.comments_on_listing.all(),
                'comment_form': CommentForm(initial= {'listing': listing,'listing_id': listing.id})
            })


    else:
        return HttpResponse("Invalid request method.")


@login_required
def comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data['listing_id']
            listing = get_object_or_404(Listing, id=listing_id)
            liisting = form.save(commit=False)
            title = listing.title
            liisting.commenter = request.user
            liisting.listing = listing
            form.save()

            return HttpResponseRedirect(reverse('current_listing',args = [title]))


@login_required
def close_auction(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    listing.Active = False
    listing.save()
    return HttpResponseRedirect(reverse('current_listing',args=[listing.title]))


@login_required
def watchlist(request):
    '''Handles the watchlistpage of the user'''
    watchlist, created = Watchlist.objects.get_or_create(watch_lister = request.user)
    listings = watchlist.watch_list_items.all().annotate(highest_bid=models.Max('bids__bid'))
    return render(request, 'auctions/watchlist.html',{
        'watchlist':watchlist,
        'listings':listings
    })

@login_required
def add_to_watchlist(request,listing_id):
    watchlist, created = Watchlist.objects.get_or_create(watch_lister = request.user)
    listing = get_object_or_404(Listing, id = listing_id)
    if watchlist.watch_list_items.filter(id = listing_id).exists():
        watchlist.watch_list_items.remove(listing)
        messages.info(request,'Listing Removed from the Watchlist.')
        return HttpResponseRedirect(reverse('current_listing',args=[listing.title]))
    else:
        watchlist.watch_list_items.add(listing)
        messages.success(request,'Listing added to the watchlist.')
        return HttpResponseRedirect(reverse('current_listing',args=[listing.title]))


def categories(request):
    catagory_list = []
    for value, label in Listing.CATEGORY_CHOICES:
        catagory_list.append(label)
    return render(request,'auctions/categories.html',{'catagory_list':catagory_list})

def category(request, category):
    if category != 'other':
        listings = Listing.objects.filter(category=category).annotate(highest_bid=models.Max('bids__bid')).filter(Active=True)
    else:
        listings = Listing.objects.filter(category= '').annotate(highest_bid=models.Max('bids__bid')).filter(Active=True)
        category = 'other catagories'
    return render(request,'auctions/category.html',{
        'listings':listings,
        'category':category})

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}
{% block title %} Categories {% endblock %}
{% block body %}
<div class="grid-cols-1 place-items-center">
    {% for category in catagory_list %}
    <div class="m-3">
        <a href="{% url 'category' category%}"><button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 w-32">{{category}}</button>
        </a>
    </div>
    {% endfor %}
    <div class="m-3">
        <a href="{% url 'category' 'other' %}"><button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 w-32">Other</button>
        </a>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block title %} {{category}}{% endblock %}
{% block body %}
    <h2 class="font-serif text-2xl text-center m-4 text-stone-800">Listings related to {{category}}</h2>
    {% for listing in listings%}
      <a href="{%url 'current_listing' listing.title%}" class="text-decoration-none">
     
        <div class="grid-cols-1 mx-1">
            <div class="border-[1px] border-solid shadow-sm flex rounded-md mb-4 hover:scale-105">
                <div class="basis-[33%]">
                    {% if listing.image_url %}
                        <div class="">
                            <img src="{{listing.image_url}}" alt="Sorry Image not available" class="max-h-[400px]">
                        </div>
                    {% else %}
                        <div class="">
                            <img src="{% static 'auctions/no_image.jpg' %}" alt="Sorry Image not available" class="max-h-[400px]">
                        </div>
                    {% endif %}           
                </div>
                <div class="basis-[66%] p-3">
                    <h1 class="text-[1.25rem] font-medium">{{listing.title}}</h1>
                    {% if listing.highest_bid %}
                    <p class="font-medium">Price: <span class="font-normal">${{listing.highest_bid}}</span></p>
                    {% else %}
                    <p class="font-medium">Price: <span class="font-normal">${{listing.starting}}</span></p>
                    {% endif %}
                    <p class="mb-4">{{listing.description| truncatewords:50}}</p>
                    <p class="opacity-70 text-sm">Created at: {{listing.time_created}}</p>
                </div>
            </div>
       
        </div>
      </a>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/current_listing.html
{% extends 'auctions/layout.html' %}
{% load static %}

{%block title%} {{title}} {% endblock %}
{%block body%}
    <div class="max-w-[1320px]">
        <h2 class="text-xl font-medium my-2 ml-2">Listing: {{listing.title}}</h2>
        <!-- <div class = 'container'> -->
            <div class="">
                {% if listing.image_url %}
                    <div class="">
                        <img src="{{listing.image_url}}" alt="Sorry Image not available" class="max-h-[400px]">
                    </div>
                {% else %}
                    <div class="">
                        <img src="{% static 'auctions/no_image.jpg' %}" alt="Sorry Image not available" class="max-h-[400px]">
                    </div>
                {% endif %}  
                {% if listing.Active == True %}
                    {% if highest_bid %}
                    <p class="font-medium text-3xl">$ {{highest_bid}}</p>
                    {% else %}
                    <p class="font-medium text-3xl">$ {{listing.starting}}</p>
                    {% endif %} 
                <div>
                    <div class="flex">
                        {% if biddings %}
                            <p class="text-sm">{{biddings}} bid(s) so far. </p>
                        {% endif %}
                        {% if highest_bidder %}
                            {% if highest_bidder == request.user %}
                                <p class="text-sm"> Your bid is the current bid.</p>
                            {% else %}
                                <p class="text-sm"> {{highest_bidder}}'s bid is the current bid.</p>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% if request.user != listing.listed_by %}
                        <form action="{%url 'bid' %}" method="post">
                            {% csrf_token %}
                            {{bidding_form}}
                    <div>
                        <button type="submit" class= " bg-stone-700 text-white px-5 cursor-pointer hover:text-black focus:ring-indigo-500 focus:border-indigo-500 mr-8 rounded-lg py-2">Place Bid</button>
                    </form>
                    <a href="{% url 'add_to_watchlist' listing.id %}">
                    <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Watchlist</button></a>

                    </div>

                    {% endif %}
                        {% if request.user == listing.listed_by %}
                            <a href="{%url 'close_auction' listing.id %}"><button class= " bg-stone-700 text-white py-2 cursor-pointer hover:text-black px-3 rounded-md focus:ring-indigo-500 focus:border-indigo-500 my-3 mr-2">Close Auction</button></a>
                            <a href="{% url 'add_to_watchlist' listing.id %}">
                                <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Watchlist</button></a>
                        {% endif %}
                {% else %}
                    {% if highest_bidder %}
                        {% if highest_bidder == request.user %}
                            <h2>Congratulations. You won the auction.</h2>
                            <a href="{% url 'add_to_watchlist' listing.id %}">
                                <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Watchlist</button></a>
                        {% else %}
                            <h2>Their were {{biddings}} bid(s) in total and {{highest_bidder}} won the auction.</h2>
                            <a href="{% url 'add_to_watchlist' listing.id %}">
                                <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Watchlist</button></a>
                        {% endif %}
                    {% else %}
                        <h2>Their was 0 zero biddings on the listing. So no one is the winner as the owner has closed the auction.</h2>
                        <a href="{% url 'add_to_watchlist' listing.id %}">
                            <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Watchlist</button></a>
                    {% endif %}
                {% endif %}
                    <div>

                    </div>
                </div>
                <p class="font-medium text-2xl">Details</p>
                <ul>
                    <p><span class="font-medium">Listed by: </span><a href="">{{listing.listed_by}}</a></p>
                    {% if listing.category %}
                        <p><span class="font-medium">Category: </span>{{listing.category}}</p>
                    {% endif %}
                    <p><span class="font-medium">Time Created: </span>{{listing.time_created}}</p>
                    <p class="mt-1 font-medium">Description:</p>
                    <p class="">{{listing.description}}</p>
                </ul>

                

                <div class="max-w-full mx-auto my-6">
                    <!-- Comment Form -->
                    <div class="bg-slate-50 p-4 rounded-lg shadow-md mb-6">
                        <h2 class="text-xl font-semibold text-gray-800 mb-4">Leave a Comment</h2>
                        <form action="{% url 'comment' %}" method="POST">
                            {% csrf_token %}
                            {{comment_form}}
                            <button
                                type="submit"
                                class="ml-[0.4rem] bg-stone-700 text-white py-2 cursor-pointer hover:text-black px-3 rounded-md focus:ring-indigo-500 focus:border-indigo-500"
                            >
                                Comment
                            </button>
                        </form>
                    </div>
                </div>
                
                    <!-- Comment Section -->
                    {% for comment in comments %}
                    <!-- Trying out the comment style -->
                    <div class="max-w-full mx-auto my-4 p-4 bg-white rounded-lg shadow-md border border-gray-200 mb-2">
                        <!-- User Info -->
                        <div class="flex items-center mb-4">
                            <!-- Profile Picture -->
                            <img
                                src="{% static 'auctions/user.png' %}"
                                alt="User Avatar"
                                class="w-10 h-10 rounded-full object-cover mr-3"
                            />
                            <div>
                                <!-- User Name -->
                                <h4 class="text-lg font-semibold text-gray-800">{{comment.commenter}}</h4>
                                <!-- Comment Timestamp -->
                                <p class="text-sm text-gray-500">Posted on {{comment.posted}}</p>
                            </div>
                        </div>
                    
                        <!-- Comment Content -->
                        <p class="text-gray-700 leading-relaxed">
                            {{comment.comment}}
                        </p>
                
                    </div>
                    {% endfor %}
                
            </div>
        <!-- </div> -->
    </div>
{%endblock%}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1 class="font-semibold text-[2rem] m-3">Active Listings</h1>
    {% for listing in listings%}
      <a href="{%url 'current_listing' listing.title%}" class="text-decoration-none">
     
        <div class="grid-cols-1 mx-1">
            <div class="border-[1px] border-solid shadow-sm flex rounded-md mb-4 hover:scale-105">
                <div class="basis-[33%]">
                    <img src="{{listing.image_url}}" alt="" class="rounded-l-md max-w-96">
                </div>
                <div class="basis-[66%] p-3">
                    <h1 class="text-[1.25rem] font-medium">{{listing.title}}</h1>
                    {% if listing.highest_bid %}
                    <p class="font-medium">Price: <span class="font-normal">${{listing.highest_bid}}</span></p>
                    {% else %}
                    <p class="font-medium">Price: <span class="font-normal">${{listing.starting}}</span></p>
                    {% endif %}
                    <p class="mb-4">{{listing.description| truncatewords:50}}</p>
                    <p class="opacity-70 text-sm">Created at: {{listing.time_created}}</p>
                </div>
            </div>
       
        </div>
      </a>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/listing.html
{%extends 'auctions/layout.html'%}



{% block title %}Create Listing{% endblock %}
{%block body%}
<h2 class="text-xl font-medium my-2 ml-2">Create Listing</h2>
<form action="{% url 'listing'%}" method="post" class="ml-2">
    {% csrf_token %}
    <div class="my-4">
        <label for="id_title" class="block font-bold text-gray-700 mb-1">Title</label>
        {{ form.title }}
    </div>
    <div class="my-4">
        <label for="id_description" class="block font-bold text-gray-700 mb-1">Description</label>
        {{ form.description }}
    </div>
    <div class="my-4">
        <label for="id_starting" class="block font-bold text-gray-700 mb-1">Starting Price</label>
        {{ form.starting }}
    </div>
    <div class="my-4">
        <label for="id_image_url" class="block font-bold text-gray-700 mb-1">Image URL</label>
        {{ form.image_url }}
    </div>
    <div class="my-4">
        <label for="id_category" class="block font-bold text-gray-700 mb-1">Category</label>
        {{ form.category }}
    </div>
    <button type="submit" class= "ml-[0.4rem] bg-stone-700 text-white py-2 cursor-pointer hover:text-black px-3 rounded-md focus:ring-indigo-500 focus:border-indigo-500">Submit</button>
</form>
{%endblock%}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="grid place-items-center">

    <h2 class="text-xl font-medium my-2 ml-2">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="m-1">
            <input autofocus class="rounded-md" type="text" name="username" placeholder="Username">
        </div>
        <div class="m-1">
            <input class="rounded-md" type="password" name="password" placeholder="Password">
        </div>
        <input class="ml-2 bg-stone-700 text-white py-[0.4rem] cursor-pointer hover:text-black px-3 rounded-md" type="submit" value="Login">
    </form>

   <p class="ml-2"> Don't have an account? <a href="{% url 'register' %}" class="text-blue-500 hover:underline">Register here.</a> </p>
</div>

{% endblock %}